version: '3'

services:
  api-server:
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      - VLLM_MODEL=codellama/CodeLlama-7b-hf
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    