name: Pipeline

on: push

jobs:
    format:
        name: Format
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'

            - name: Setup pip and dependencies
              run: |
                python -m pip install --upgrade pip
                pip install poetry

            - name: Setup poetry
              run: |
                poetry install

            - name: Run black
              run: |
                poetry run invoke formatting

            
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'

            - name: Setup pip and dependencies
              run: |
                python -m pip install --upgrade pip
                pip install poetry

            - name: Setup poetry
              run: |
                poetry install

            - name: Run tests
              run: |
                poetry run invoke coverage

            - name: Coveralls
              uses: coverallsapp/github-action@v2
              