name: Publish

on: 
    release:
        types: [created]

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'

            - name: Setup pip and dependencies
              run: |
                python -m pip install --upgrade pip
                pip install poetry

            - name: Configure poetry for publishing
              run: |
                poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

            - name: Build and publish
              run: |
                poetry --build publish